export const mockApplicants = [
  {
    id: "mock-1",
    fullName: "Сударєв Віталій Геннадійович",
    lastName: "Сударєв",
    firstName: "Віталій",
    middleName: "Геннадійович",
    gender: "Чоловіча",
    phone: "0685871747",
    birthDate: "14.03.1996",
    university: "Поліський національний університет",
    tcc: "Житомирський ОМТЦК та СП",
    vosDesired: "СРЗ (Застосування засобів спеціального радіозв'язку)",
    vosAlternative: "РЕБ (Застосування засобів радіоелектронної боротьби)",
    gradeRaw: "74",
    grade: 74,
    militaryService: "Так",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    rawPhotoUrl: "",
    timestamp: "08.04.2026 11:07:35"
  },
  {
    id: "mock-2",
    fullName: "Лавренюк Єлизавета Олександрівна",
    lastName: "Лавренюк",
    firstName: "Єлизавета",
    middleName: "Олександрівна",
    gender: "Жіноча",
    phone: "+380666863665",
    birthDate: "14.01.2002",
    university: "КВНЗ «Житомирський базовий фармацевтичний коледж»",
    tcc: "На обліку не перебуваю",
    vosDesired: "не визначився (не визначилась), потребую додаткової консультації",
    vosAlternative: "не визначився (не визначилась)",
    gradeRaw: "Не вказано",
    grade: 0,
    militaryService: "Ні",
    photoUrl: "",
    rawPhotoUrl: "",
    timestamp: "09.04.2026 15:54:41"
  },
  {
    id: "mock-3",
    fullName: "Журавський Артур Петрович",
    lastName: "Журавський",
    firstName: "Артур",
    middleName: "Петрович",
    gender: "Чоловіча",
    phone: "+38 068 419 46 03",
    birthDate: "13.04.2006",
    university: "Державний університет «Житомирська політехніка»",
    tcc: "Житомирський ОМТЦК та СП",
    vosDesired: "БпАК (Застосування безпілотних авіаційних комплексів)",
    vosAlternative: "РЕБ (Застосування засобів радіоелектронної боротьби)",
    gradeRaw: "86 за минулий семестр",
    grade: 86,
    militaryService: "Ні",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    rawPhotoUrl: "",
    timestamp: "10.04.2026 09:18:43"
  },
  {
    id: "mock-4",
    fullName: "Столяров Артем Сергійович",
    lastName: "Столяров",
    firstName: "Артем",
    middleName: "Сергійович",
    gender: "Чоловіча",
    phone: "+380975060830",
    birthDate: "07.08.2005",
    university: "Державний університет «Житомирська політехніка»",
    tcc: "Бердичівський РТЦК та СП",
    vosDesired: "РЕБ (Застосування засобів радіоелектронної боротьби)",
    vosAlternative: "БпАК (Застосування безпілотних авіаційних комплексів)",
    gradeRaw: "91",
    grade: 91,
    militaryService: "Ні",
    photoUrl: "",
    rawPhotoUrl: "",
    timestamp: "13.04.2026 16:31:42"
  },
  {
    id: "mock-5",
    fullName: "Чагарова Сніжана Миколаївна",
    lastName: "Чагарова",
    firstName: "Сніжана",
    middleName: "Миколаївна",
    gender: "Жіноча",
    phone: "0689986100",
    birthDate: "19.10.2006",
    university: "Державний університет «Житомирська політехніка»",
    tcc: "На обліку не перебуваю",
    vosDesired: "БпАК (Застосування безпілотних авіаційних комплексів)",
    vosAlternative: "БпАК (Застосування безпілотних авіаційних комплексів)",
    gradeRaw: "≈89,4",
    grade: 89.4,
    militaryService: "Ні",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    rawPhotoUrl: "",
    timestamp: "15.04.2026 10:14:53"
  },
  {
    id: "mock-6",
    fullName: "Ковальчук Ольга Віталіївна",
    lastName: "Ковальчук",
    firstName: "Ольга",
    middleName: "Віталіївна",
    gender: "Жіноча",
    phone: "0983214233",
    birthDate: "06.09.1999",
    university: "Житомирський агротехнічний коледж",
    tcc: "На обліку не перебуваю",
    vosDesired: "не визначився (не визначилась), потребую додаткової консультації",
    vosAlternative: "не визначився (не визначилась)",
    gradeRaw: "96",
    grade: 96,
    militaryService: "Ні",
    photoUrl: "",
    rawPhotoUrl: "",
    timestamp: "15.04.2026 14:12:58"
  },
  {
    id: "mock-7",
    fullName: "Маніхровський Ярослав Олександрович",
    lastName: "Маніхровський",
    firstName: "Ярослав",
    middleName: "Олександрович",
    gender: "Чоловіча",
    phone: "+380676657451",
    birthDate: "12.03.2007",
    university: "Державний університет «Житомирська політехніка»",
    tcc: "Житомирський ОМТЦК та СП",
    vosDesired: "БпАК (Застосування безпілотних авіаційних комплексів)",
    vosAlternative: "БпАК (Застосування безпілотних авіаційних комплексів)",
    gradeRaw: "≈ 92,52",
    grade: 92.52,
    militaryService: "Ні",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    rawPhotoUrl: "",
    timestamp: "16.04.2026 19:49:37"
  },
  {
    id: "mock-8",
    fullName: "Хімчик Анастасія Олексіївна",
    lastName: "Хімчик",
    firstName: "Анастасія",
    middleName: "Олексіївна",
    gender: "Жіноча",
    phone: "+380974127630",
    birthDate: "03.12.2005",
    university: "Національний університет «Львівська Політехніка»",
    tcc: "На обліку не перебуваю",
    vosDesired: "СРЗ (Застосування засобів спеціального радіозв'язку)",
    vosAlternative: "не визначився (не визначилась)",
    gradeRaw: "95,3",
    grade: 95.3,
    militaryService: "Ні",
    photoUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80",
    rawPhotoUrl: "",
    timestamp: "23.04.2026 16:42:28"
  },
  {
    id: "mock-9",
    fullName: "Кучерук Ілля Вікторович",
    lastName: "Кучерук",
    firstName: "Ілля",
    middleName: "Вікторович",
    gender: "Чоловіча",
    phone: "0963915262",
    birthDate: "04.10.2005",
    university: "Національний університет «Львівська Політехніка»",
    tcc: "Хмельницький ОМТЦК та СП",
    vosDesired: "СРЗ (Застосування засобів спеціального радіозв'язку)",
    vosAlternative: "не визначився (не визначилась)",
    gradeRaw: "94.9",
    grade: 94.9,
    militaryService: "Ні",
    photoUrl: "",
    rawPhotoUrl: "",
    timestamp: "23.04.2026 16:46:33"
  },
  {
    id: "mock-10",
    fullName: "Шевчук Ярослав Андрійович",
    lastName: "Шевчук",
    firstName: "Ярослав",
    middleName: "Андрійович",
    gender: "Чоловіча",
    phone: "+380961508049",
    birthDate: "24.12.2006",
    university: "Національний юридичний університет імені Ярослава Мудрого",
    tcc: "Житомирський обласний ТЦК та СП",
    vosDesired: "БпАК (Застосування безпілотних авіаційних комплексів)",
    vosAlternative: "РЕБ (Застосування засобів радіоелектронної боротьби)",
    gradeRaw: "95,3",
    grade: 95.3,
    militaryService: "Ні",
    photoUrl: "",
    rawPhotoUrl: "",
    timestamp: "24.04.2026 16:43:44"
  }
];
